konesh_session_types:
  دعوت نزدیکان به سایت اصلی: فشرده
  فضاسازی خانه: مبسوط
  بیان آیه در سفره: فشرده
  محفل خانگی: مبسوط
  قصه شب قرآنی: مبسوط
  همخوانی سوره قدر: مبسوط
  پانتومیم آیه: مبسوط
  مهمونی قرآنی: مبسوط
  تابلوی دکوراتیو: مبسوط
  فضاسازی اتاق کودک: مبسوط
  حلقه کتاب‌خوانی: مبسوط
  محفل مسجدی: مبسوط
  آیه بین دو نماز: فشرده
  آیه قبل از جزء‌خوانی: فشرده
  میز مطالعه مسجد: مبسوط
  گوشه کودکانه آیه‌ها: مبسوط
  منبر موج‌آفرین: مبسوط
  محفل در محله: مبسوط
  ارائه کوتاه آیه در کلاس: مبسوط
  آیه هفته (تخته کلاس): فشرده
  آیه صبحگاه: فشرده
  آیه در اتاق معلمان: مبسوط
  کد معرف و دعوت به سایت: فشرده
  مأموریت آیه: مبسوط
  نمایش مفهومی: مبسوط
  جنگ قرآنی: مبسوط
  کاردستی قرآنی: مبسوط
  کارگاه چالش آیه‌ها: مبسوط
  محفل در مدرسه: مبسوط
  انتشار محتواهای زندگی با آیه ها در فضای مجازی: مبسوط
  پویش قاب پروفایل: مبسوط
  پس‌زمینه آیه: مبسوط
  پیام در اتاق گفتگو: مبسوط
  'چالش #قرار_من_با_قرآن': مبسوط
  نظرسنجی و کوئیز آیه: مبسوط
  صدا-پیام آیه: مبسوط
  'روایت #آیه_زندگی_من': مبسوط
  دکلمه آیه: مبسوط
  لایو مشترک: مبسوط
  نگارخانه آیه: مبسوط
  تحلیل روز با آیه‌ها: مبسوط
  تولید کلیپ آیه: مبسوط
  انرژی‌بخش رومیزی: مبسوط
  اتاق انتظار آیه‌ها: مبسوط
  شیشه-نوشته خودرو: مبسوط
  حلقه کتاب‌خوانی در محیط کار/دانشگاه: مبسوط
  جوخه عمل: مبسوط
  همخوانی در باشگاه: مبسوط
  دیالوگ آکادمیک: مبسوط
  سفیر سفیران: مبسوط
