konesh_session_types:
  تماس تلفنی قرآنی: مبسوط
  محفل زندگی با آیه‌ها در خانه: مبسوط
  پانتومیم آیه: مبسوط
  جمع‌خوانی کتاب آیه‌ها: مبسوط
  سفره قرآنی: فشرده
  فضاسازی قرآنی: مبسوط
  قصه شب قرآنی: مبسوط
  دیوارنویسی آیه‌ها: مبسوط
  سرود آیه‌ها: مبسوط
  موکب آیه‌ها: مبسوط
  آیه در کافه: مبسوط
  پشت‌نویسی آیه روی خودرو: مبسوط
  تابلوی  قرآنی همسایگی: مبسوط
  خودروی قرآنی: مبسوط
  دفتر کار قرآنی: مبسوط
  مغازه قرآنی با برکت: مبسوط
  همخوانی قرآنی در باشگاه: مبسوط
  دعوت به زندگی به آیه‌ها: مبسوط
  محتوای قرآنی در فضای مجازی: مبسوط
  تحلیل اخبار با آیه‌ها: مبسوط
  'روایت #آیه_زندگی_من': مبسوط
  عطر هنر آیه‌‌ها: مبسوط
  'قاب #ساعت_قرآن': مبسوط
  استیکر و آویز آیه‌ها: مبسوط
  آیه روی تخته: مبسوط
  نامه‌ای به خدا: مبسوط
  تریبون آزاد قرآنی: مبسوط
  جُنگ قرآنی: مبسوط
  نمایشگاه آیه‌ها در مسجد: مبسوط
  ارائه یا نمایش آیه: مبسوط
  آیه در اتاق معلمان: مبسوط
  آیه در صبحگاه: فشرده
  سینما آیه‌ها: مبسوط
  کاردستی قرآنی: مبسوط
  میز مطالعه آیه‌ها: مبسوط
  پرده‌خوانی آیه‌ها: مبسوط
  محفل زندگی با آیه‌ها در مسجد: مبسوط
  مسجد پایگاه قرآن: مبسوط
  نمایشگاه زندگی با آیه‌ها در مسجد: مبسوط
  تبیین آیه در نماز جماعت: مبسوط
  توضیح آیه در جزء‌خوانی: فشرده
  دیدار قرآنی با خانواده شهدا: مبسوط
  کتابخوانی آیه‌ها با مسجدی‌ها: مبسوط
  گوشه کودکانه آیه‌ها: مبسوط
