special_actions:
- id: 1
  name: بسم الله
  session_type: مبسوط
- id: 2
  name: فهرست کنش‌های ویژه
  session_type: مبسوط
- id: 3
  name: ۱. کنش‌های ویژه خانگی
  session_type: مبسوط
- id: 4
  name: ۱. صله رحم قرآنی
  session_type: مبسوط
- id: 5
  name: 'بستر: ارتباطات تلفنی و راه دور (تلفن ثابت یا همراه).'
  session_type: مبسوط
- id: 6
  name: 'کنش‌گر: بانوان و مادران (توسط آقایان و جوانان نیز قابل انجام است).'
  session_type: مبسوط
- id: 7
  name: 'مخاطب کنش: اقوام، ارحام، دوستان قدیمی و بزرگترهای فامیل.'
  session_type: مبسوط
- id: 8
  name: 'معرفی: استفاده از فرصت مکالمات تلفنی روزمره و صله رحم برای انتقال یک پیام
    کوتاه، امیدبخش و معنوی از '
  session_type: مبسوط
- id: 9
  name: 'فرم (الگوی اجرا): سفیر قبل از تماس، یک جمله یا پیام کوتاه از «آیه منتخب روز»
    را آماده می‌کند. در حین'
  session_type: مبسوط
- id: 10
  name: 'محتوا:'
  session_type: مبسوط
- id: 11
  name: 'محتوای مکتوب: استفاده از متن‌های ۱۰۰ کلمه‌ای روان موجود در «کتابچه زندگی
    با آیه‌ها» یا بخش‌های کوتاه'
  session_type: مبسوط
- id: 12
  name: 'دستیار هوشمند: سفیر می‌تواند از هوش مصنوعی بخواهد: «پیام آیه [متن آیه] را
    به یک جمله صمیمی و محاوره '
  session_type: مبسوط
- id: 13
  name: 'ویژگی: ادغام شدن در رفتار موجود (صله رحم)؛ بسیار گرم، شخصی و دارای اثرگذاری
    عاطفی بالا بر روی مخاطبا'
  session_type: مبسوط
- id: 14
  name: ۲. محفل زندگی با آیه‌ها در خانه
  session_type: مبسوط
- id: 15
  name: 'بستر: فضای داخلی خانه (پذیرایی).'
  session_type: مبسوط
- id: 16
  name: 'کنش‌گر: عموم مردم، خانواده‌ها (به‌ویژه بانوان).'
  session_type: مبسوط
- id: 17
  name: 'مخاطب کنش: اعضای فامیل، همسایگان، دوستان نزدیک.'
  session_type: مبسوط
- id: 18
  name: 'معرفی: برگزاری یک دورهمی ساده و بی‌تکلف (هفتگی یا ماهانه) در منزل با محوریت
    قرآن، که در آن علاوه بر '
  session_type: مبسوط
- id: 19
  name: 'فرم (الگوی اجرا): میزبان (سفیر) از مهمانان دعوت می‌کند. سفیر جلسه را با استفاده
    از الگوی «هسته سخت» '
  session_type: مبسوط
- id: 20
  name: 'محتوا:'
  session_type: مبسوط
- id: 21
  name: 'محتوای مکتوب: استفاده از «کتاب اصلی»، «کتاب ستاره‌های زمین (درسنامه جلسات)»
    برای مدیریت جلسه یا «منب'
  session_type: مبسوط
- id: 22
  name: 'دستیار هوشمند: درخواست از هوش مصنوعی برای: «تولید محتوای تبیین امروزی و اتصال
    به عمل متناسب با جزییا'
  session_type: مبسوط
- id: 23
  name: 'ویژگی: ایجاد سنت حسنه و پایدار؛ تبدیل خانه به پایگاه نور؛ تقویت روابط اجتماعی
    و دینی در بستر امن خان'
  session_type: مبسوط
- id: 24
  name: ۳. فضاسازی قرآنی خانه
  session_type: مبسوط
- id: 25
  name: 'بستر: نقاط مختلف خانه (درب یخچال، دیوار پذیرایی، طاقچه، کابینت آشپزخانه).'
  session_type: مبسوط
- id: 26
  name: 'کنش‌گر: بانوان (مادر یا دختر خانواده).'
  session_type: مبسوط
- id: 27
  name: 'مخاطب کنش: تمام اعضای خانواده (همسر و فرزندان) و مهمانان.'
  session_type: مبسوط
- id: 28
  name: 'معرفی: اختصاص بخش‌هایی از فضای فیزیکی و دکوراسیون منزل به نمایش هنرمندانه
    و مستمر پیام‌های قرآنی برا'
  session_type: مبسوط
- id: 29
  name: 'فرم (الگوی اجرا):'
  session_type: مبسوط
- id: 30
  name: 'مگنت/کابینت: نصب مگنت‌های سریالی یا برگه‎های زیبا با پیام‌های کوتاه (شکر،
    رزق) روی یخچال یا کابینت آ'
  session_type: مبسوط
- id: 31
  name: 'طاقچه معنوی: اختصاص یک میز یا طاقچه برای قرار دادن قرآن، شمع و کارت «آیه
    هفته».'
  session_type: مبسوط
- id: 32
  name: 'دیوار قرآنی: نصب تابلوهای دکوراتیو مدرن یا تایپوگرافی آیات روی دیوار.'
  session_type: مبسوط
- id: 33
  name: 'محتوا:'
  session_type: مبسوط
- id: 34
  name: 'محتوای مکتوب: استفاده از تایپوگرافی‌های «کتاب ادبی هنری» یا جملات کوتاه «مصحف
    زندگی با آیه‌ها».'
  session_type: مبسوط
- id: 35
  name: 'دستیار هوشمند: درخواست از هوش مصنوعی برای: «پیشنهاد جملات کوتاه و انگیزشی
    از آیه [نام آیه] مناسب برا'
  session_type: مبسوط
- id: 36
  name: 'ویژگی: استفاده از هنر و زیبایی‌شناسی برای انتقال پیام؛ تأثیرگذاری ناخودآگاه
    و دائمی بر اعضای خانواده'
  session_type: مبسوط
- id: 37
  name: ۴. سفره قرآنی
  session_type: مبسوط
- id: 38
  name: 'بستر: سفره غذا (به‌ویژه سفره افطار).'
  session_type: مبسوط
- id: 39
  name: 'کنش‌گر: والدین (یا فرزندان).'
  session_type: مبسوط
- id: 40
  name: 'مخاطب کنش: تمام اعضای خانواده دور سفره.'
  session_type: مبسوط
- id: 41
  name: 'معرفی: تبدیل لحظات دورهمی گرم و صمیمی سر سفره به فرصتی برای تلاوت و فهم قرآن.'
  session_type: مبسوط
- id: 42
  name: 'فرم (الگوی اجرا):'
  session_type: مبسوط
- id: 43
  name: 'همخوانی: درست قبل از افطار، همه اعضا با هم سوره «قدر» را همخوانی می‌کنند
    (سنت مأثور).'
  session_type: مبسوط
- id: 44
  name: 'پیام آیه: پیش از شروع غذا، پدر یا مادر یک نکته ۳۰ ثانیه‌ای از «آیه منتخب
    روز» (مثلاً درباره برکت، ان'
  session_type: مبسوط
- id: 45
  name: 'محتوا:'
  session_type: مبسوط
- id: 46
  name: 'محتوای مکتوب: متن سوره قدر + پیام‌های کوتاه «کتابچه زندگی با آیه‌ها».'
  session_type: مبسوط
- id: 47
  name: 'دستیار هوشمند: درخواست از هوش مصنوعی برای: «یک نکته تربیتی کوتاه درباره "رزق
    حلال" بر اساس آیه روز ب'
  session_type: مبسوط
- id: 48
  name: 'ویژگی: پیوند زدن نیاز جسمانی (غذا) با نیاز روحانی (قرآن)؛ احیای سنت‌های فراموش‌شده؛
    استفاده از زمان '
  session_type: مبسوط
- id: 49
  name: ۲. کنش‌های ویژه مدرسه
  session_type: مبسوط
- id: 50
  name: ۵. کد معرف و دعوت (سفیرِ سفیران)
  session_type: مبسوط
- id: 51
  name: 'بستر: مدرسه، سایت زندگی با آیه‌ها، گروه‌های کلاسی.'
  session_type: مبسوط
- id: 52
  name: 'کنش‌گر: دانش‌آموزان فعال، معلمان.'
  session_type: مبسوط
- id: 53
  name: 'مخاطب کنش: همکلاسی‌ها، دوستان، والدین دانش‌آموزان.'
  session_type: مبسوط
- id: 54
  name: 'معرفی: ترغیب دیگران به ثبت‌نام در سامانه سفیران و پیوستن به نهضت با استفاده
    از سیستم ارجاع.'
  session_type: مبسوط
- id: 55
  name: 'فرم (الگوی اجرا): دانش‌آموز در سایت ثبت‌نام کرده و «کد معرف» یا «لینک اختصاصی»
    دریافت می‌کند. او با '
  session_type: مبسوط
- id: 56
  name: 'محتوا:'
  session_type: مبسوط
- id: 57
  name: 'محتوای مکتوب: استفاده از توضیحات جذاب «مجله جیبی» برای معرفی طرح.'
  session_type: مبسوط
- id: 58
  name: 'دستیار هوشمند: درخواست از هوش مصنوعی برای: «نوشتن یک متن دعوت جذاب و هیجانی
    برای دانش‌آموزان جهت عضو'
  session_type: مبسوط
- id: 59
  name: 'ویژگی: شبکه‌سازی و گسترش تصاعدی تعداد مخاطبان؛ ایجاد حس رقابت مثبت و هویت‌بخشی
    به دانش‌آموز به عنوان'
  session_type: مبسوط
- id: 60
  name: ۶. آیه در صبحگاه
  session_type: مبسوط
- id: 61
  name: 'بستر: حیاط مدرسه (مراسم صبحگاه).'
  session_type: مبسوط
- id: 62
  name: 'کنش‌گر: دانش‌آموزان (شورای دانش‌آموزی/بسیج)، مربی پرورشی.'
  session_type: مبسوط
- id: 63
  name: 'مخاطب کنش: کل دانش‌آموزان مدرسه.'
  session_type: مبسوط
- id: 64
  name: 'معرفی: گنجاندن بخش ثابت و جذاب تبیین آیه در برنامه روتین صبحگاه.'
  session_type: مبسوط
- id: 65
  name: 'فرم (الگوی اجرا): هر روز صبح، پس از قرآن ابتدایی، یک دانش‌آموز مسلط (سفیر)
    پشت تریبون می‌رود. او «آی'
  session_type: مبسوط
- id: 66
  name: 'محتوا:'
  session_type: مبسوط
- id: 67
  name: 'محتوای مکتوب: استفاده از محتوای «منبر نوجوان» یا «طرح درس نوجوان».'
  session_type: مبسوط
- id: 68
  name: 'دستیار هوشمند: درخواست از هوش مصنوعی برای: «طراحی یک سوال مسابقه کوتاه و
    جذاب بر اساس آیه [نام آیه] '
  session_type: مبسوط
- id: 69
  name: 'ویژگی: فراگیری بالا (شنیده شدن توسط همه)؛ رسمیت بخشیدن به گفتمان آیه در فضای
    عمومی مدرسه.'
  session_type: مبسوط
- id: 70
  name: ۷. نمایش یا ارائه کلاسی
  session_type: مبسوط
- id: 71
  name: 'بستر: کلاس درس (زنگ تفریح، زنگ پرورشی یا دینی).'
  session_type: مبسوط
- id: 72
  name: 'کنش‌گر: دانش‌آموزان (تکی یا گروهی).'
  session_type: مبسوط
- id: 73
  name: 'مخاطب کنش: همکلاسی‌ها.'
  session_type: مبسوط
- id: 74
  name: 'معرفی: اجرای فعالیت‌های هنری و نمایشی برای انتقال مفاهیم آیات به زبان همسالان.'
  session_type: مبسوط
- id: 75
  name: 'فرم (الگوی اجرا):'
  session_type: مبسوط
- id: 76
  name: 'نمایش: اجرای یک تئاتر کوتاه طنز یا جدی (۵ دقیقه‌ای) بر اساس داستان یا مفهوم
    آیه.'
  session_type: مبسوط
- id: 77
  name: 'ارائه: دانش‌آموز پای تخته می‌رود و کنفرانس کوتاهی درباره ربط آیه به مسائل
    نوجوانان می‌دهد و یا بخشی '
  session_type: مبسوط
- id: 78
  name: 'محتوا:'
  session_type: مبسوط
- id: 79
  name: 'محتوای مکتوب: استفاده از داستان‌های «کتاب داستان هانی» یا «کتاب شهادت آیه‌ها»
    به عنوان نمایشنامه یا '
  session_type: مبسوط
- id: 80
  name: 'دستیار هوشمند: درخواست از هوش مصنوعی برای: «نوشتن یک نمایشنامه طنز کوتاه
    مدرسه ای بر اساس مفهوم آیه '
  session_type: مبسوط
- id: 81
  name: 'ویژگی: جذابیت فوق‌العاده برای نوجوانان؛ یادگیری عمیق از طریق «اجرا کردن»؛
    تبدیل کلاس خشک به فضای تعا'
  session_type: مبسوط
- id: 82
  name: ۳. کنش‌های ویژه مسجد
  session_type: مبسوط
- id: 83
  name: ۸. محفل زندگی با آیه‌ها در مسجد
  session_type: مبسوط
- id: 84
  name: 'بستر: شبستان مسجد.'
  session_type: مبسوط
- id: 85
  name: 'کنش‌گر: امام جماعت، فعالان فرهنگی (توسط آقایان و بانوان).'
  session_type: مبسوط
- id: 86
  name: 'مخاطب کنش: نمازگزاران و اهالی محله.'
  session_type: مبسوط
- id: 87
  name: 'معرفی: برگزاری محفل زندگی با آیه‌ها در مسجد.'
  session_type: مبسوط
- id: 88
  name: 'فرم (الگوی اجرا): در زمان مشخص (مثلاً بعد از نماز عشا)، یا بعد از نماز ظهر
    و عصر در ماه رمضان، محفل '
  session_type: مبسوط
- id: 89
  name: 'محتوا:'
  session_type: مبسوط
- id: 90
  name: 'محتوای مکتوب: «کتاب ستاره‌های زمین» یا «منبر عمومی».'
  session_type: مبسوط
- id: 91
  name: 'دستیار هوشمند: درخواست از هوش مصنوعی برای: «تولید محتوای اختصاصی متناسب با
    فرم محفل زندگی با آیه‌ها '
  session_type: مبسوط
- id: 92
  name: 'ویژگی: ایجاد پایگاه اجتماعی و معرفتی؛ تعمیق مفاهیم دینی در بین متدینین.'
  session_type: مبسوط
- id: 93
  name: ۹. آیه در جزء‌خوانی
  session_type: مبسوط
- id: 94
  name: 'بستر: مراسم جزء‌خوانی روزانه (رمضان).'
  session_type: مبسوط
- id: 95
  name: 'کنش‌گر: قاریان، مفسر یا امام جماعت.'
  session_type: مبسوط
- id: 96
  name: 'مخاطب کنش: شرکت‌کنندگان در جزء‌خوانی.'
  session_type: مبسوط
- id: 97
  name: 'معرفی: غنی‌سازی مراسم تلاوت قرآن با تدبر کوتاه در آیه منتخب روز.'
  session_type: مبسوط
- id: 98
  name: 'فرم (الگوی اجرا): قبل از شروع جزء‌خوانی سفیر ۳ تا ۵ دقیقه درباره «آیه منتخب
    همان روز» (که در آن جزء '
  session_type: مبسوط
- id: 99
  name: 'محتوا:'
  session_type: مبسوط
- id: 100
  name: 'محتوای مکتوب: نکات کوتاه حاشیه «مصحف زندگی با آیه‌ها» یا متن کتاب اصلی.'
  session_type: مبسوط
- id: 101
  name: 'دستیار هوشمند: درخواست از هوش مصنوعی برای: «خلاصه‌سازی پیام اصلی آیه [نام
    آیه] در ۳ نکته کلیدی برای '
  session_type: مبسوط
- id: 102
  name: 'ویژگی: پیوند دادن «قرائت» با «فهم»؛ استفاده از جمعیت آماده و مشتاق در ماه
    رمضان.'
  session_type: مبسوط
- id: 103
  name: ۱۰. تبدیل مسجد به پایگاه قرآنی
  session_type: مبسوط
- id: 104
  name: 'بستر: کل فضای مسجد و محله پیرامون.'
  session_type: مبسوط
- id: 105
  name: 'کنش‌گر: فعالان مسجد، امام جماعت، هیئت امنا.'
  session_type: مبسوط
- id: 106
  name: 'مخاطب کنش: عموم مردم محله (حتی کسانی که کمتر به مسجد می‌آیند).'
  session_type: مبسوط
- id: 107
  name: 'معرفی: یک پروژه جامع برای تغییر اتمسفر و کارکرد مسجد از «نمازخانه صرف» به
    «مرکز نشر قرآن» در محله.'
  session_type: مبسوط
- id: 108
  name: 'فرم (الگوی اجرا): مجموعه‌ای از اقدامات هماهنگ:'
  session_type: مبسوط
- id: 109
  name: 'فضاسازی: نصب بنرها و پوسترهای آیات منتخب در ورودی و نمای بیرونی.'
  session_type: مبسوط
- id: 110
  name: 'آموزش: برگزاری کلاس‌های متنوع (روخوانی، حفظ، تدبر) برای سنین مختلف.'
  session_type: مبسوط
- id: 111
  name: 'مسابقات: اجرای لیگ‌های قرآنی و مسابقات هفتگی بین نوجوانان محله.'
  session_type: مبسوط
- id: 112
  name: 'محفل هفتگی: تثبیت یک شب در هفته به عنوان شب انس با قرآن.'
  session_type: مبسوط
- id: 113
  name: 'محتوا:'
  session_type: مبسوط
- id: 114
  name: 'محتوای مکتوب: استفاده از تمام ظرفیت‌ها شامل «طرح درس کودک و نوجوان»، «منبر
    عمومی» و پوسترها.'
  session_type: مبسوط
- id: 115
  name: 'دستیار هوشمند: درخواست از هوش مصنوعی برای: «ارائه ۵ ایده خلاقانه برای جذب
    نوجوانان محله به فعالیت‌ها'
  session_type: مبسوط
- id: 116
  name: 'ویژگی: جریان‌سازی کلان؛ تغییر هویت محله؛ ایجاد فضای تنفس معنوی برای اهالی.'
  session_type: مبسوط
- id: 117
  name: ۴. کنش‌های ویژه فضای مجازی
  session_type: مبسوط
- id: 118
  name: ۱۱. ارسال محتوا در پیج‌ها، کانال‌ها و گروه‌ها (نشر حداکثری)
  session_type: مبسوط
- id: 119
  name: 'بستر: پیام‌رسان‌ها (ایتا، بله، روبیکا، تلگرام، واتس‌اپ، اینستاگرام و...)
    – پیج، کانال و گروه‌های خان'
  session_type: مبسوط
- id: 120
  name: 'کنش‌گر: عموم مردم (همه کسانی که گوشی هوشمند دارند).'
  session_type: مبسوط
- id: 121
  name: 'مخاطب کنش: اعضای گروه‌ها و مخاطبین شخصی.'
  session_type: مبسوط
- id: 122
  name: 'معرفی: توزیع مویرگی محتواهای تولید شده توسط نهضت.'
  session_type: مبسوط
- id: 123
  name: 'فرم (الگوی اجرا): سفیر محتواهای جذاب (کلیپ، عکس‌نوشت، پادکست) را از کانال
    اصلی برمی‌دارد و با یک خط '
  session_type: مبسوط
- id: 124
  name: 'محتوا:'
  session_type: مبسوط
- id: 125
  name: 'محتوای مکتوب: استفاده از محتواهای کوتاه «مجله رسانه‌ای‌ها» و سایر تولیدات
    رسانه‌ای نهضت زندگی با آیه'
  session_type: مبسوط
- id: 126
  name: 'دستیار هوشمند: درخواست از هوش مصنوعی برای: «نوشتن یک کپشن کوتاه و ترغیب‌کننده
    برای ارسال ویدیوی آیه '
  session_type: مبسوط
- id: 127
  name: 'ویژگی: سرعت و گستردگی بسیار بالا؛ هزینه صفر؛ استفاده از شبکه اعتماد شخصی
    افراد.'
  session_type: مبسوط
- id: 128
  name: ۱۲. استوری و استاتوس
  session_type: مبسوط
- id: 129
  name: 'بستر: اینستاگرام، واتس‌اپ، بله و تمامی اپ‌هایی که قابلیت ایجاد استوری یا
    استاتوس دارند.'
  session_type: مبسوط
- id: 130
  name: 'کنش‌گر: عموم مردم (همه کسانی که گوشی هوشمند دارند).'
  session_type: مبسوط
- id: 131
  name: 'مخاطب کنش: دنبال‌کنندگان (Followers) و مخاطبین تلفن همراه.'
  session_type: مبسوط
- id: 132
  name: 'معرفی: تبدیل صفحه شخصی به یک تریبون قرآنی روزانه.'
  session_type: مبسوط
- id: 133
  name: 'فرم (الگوی اجرا): سفیر هر روز «پوستر باکیفیت آیه روز» یا یک «عکس‌نوشت هنری»
    را استوری یا استاتوس می‌'
  session_type: مبسوط
- id: 134
  name: 'محتوا:'
  session_type: مبسوط
- id: 135
  name: 'محتوای مکتوب: تصاویر و متن‌های «مجله جیبی» و سایر تولیدات رسانه‌ای نهضت زندگی
    با آیه‌ها.'
  session_type: مبسوط
- id: 136
  name: 'دستیار هوشمند: درخواست از هوش مصنوعی برای: «طراحی یک سوال چهارگزینه‌ای (کوییز)
    بر اساس مفهوم آیه روز'
  session_type: مبسوط
- id: 137
  name: 'ویژگی: دیده شدن مکرر؛ ایجاد موج رسانه‌ای یکپارچه؛ حفظ یاد قرآن در لابه‌لای
    روزمرگی‌های مجازی.'
  session_type: مبسوط
- id: 138
  name: ۱۳. اَد استوری (Add Story)
  session_type: مبسوط
- id: 139
  name: 'بستر: اینستاگرام.'
  session_type: مبسوط
- id: 140
  name: 'کنش‌گر: کاربران اینستاگرام.'
  session_type: مبسوط
- id: 141
  name: 'مخاطب کنش: دنبال‌کنندگان سفیر.'
  session_type: مبسوط
- id: 142
  name: 'معرفی: بازنشر سریع و زنجیره‌ای استوری‌های پیج اصلی.'
  session_type: مبسوط
- id: 143
  name: 'فرم (الگوی اجرا):'
  session_type: مبسوط
- id: 144
  name: سفیر ابتدا پیج اصلی «زندگی با آیه‌ها» را فالو می‌کند.
  session_type: مبسوط
- id: 145
  name: پیج اصلی استوری‌هایی با قالب "Add Yours" یا استوری‌های جذاب می‌گذارد.
  session_type: مبسوط
- id: 146
  name: سفیر با زدن دکمه "Add to your story" آن محتوا را عیناً در پیج خود بازنشر می‌دهد.
  session_type: مبسوط
- id: 147
  name: 'محتوا: محتوای تولیدی پیج مرجع.'
  session_type: مبسوط
- id: 148
  name: 'دستیار هوشمند: (در اینجا نقش کمتری دارد، زیرا محتوا آماده است، اما می‌تواند
    برای نوشتن متن روی استور'
  session_type: مبسوط
- id: 149
  name: 'ویژگی: آسان‌ترین و سریع‌ترین کنش مجازی؛ ایجاد اتحاد بصری؛ هدایت مخاطبان به
    سمت منبع اصلی محتوا.'
  session_type: مبسوط
